# Generated by Django 4.2 on 2023-04-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
